[package]
name = "locus-app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "GUI application for Locus"

[[bin]]
name = "locus-app"
path = "src/main.rs"

[dependencies]
locus-core = { path = "../locus-core", version = "0.0.1" }
